[package]
name = "club_server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.2"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
ic-stable-structures = "0.5.6"
prost = "0.11.9"
serde = "1.0.160"

[dev-dependencies]
async-std = "1.12.0"